const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("desktop", {
  isDesktop: true,
  openSectionWindow: (payload) => ipcRenderer.invoke("open-section-window", payload),
  updateSectionWindow: (payload) => ipcRenderer.invoke("update-section-window", payload),
  sendSectionSnapshot: (payload) => ipcRenderer.invoke("section-snapshot", payload),
  onSectionSnapshot: (cb) => { const h = (_e, d) => cb(d); ipcRenderer.on("section-snapshot", h); return () => ipcRenderer.removeListener("section-snapshot", h); },
  sendSectionContacts: (payload) => ipcRenderer.invoke("section-contacts", payload),
  onSectionContacts: (cb) => { const h = (_e, d) => cb(d); ipcRenderer.on("section-contacts", h); return () => ipcRenderer.removeListener("section-contacts", h); },
  exportPDF: (payload) => ipcRenderer.invoke("export-pdf", payload),
  saveFile: (payload) => ipcRenderer.invoke("save-file", payload),
  openFile: (payload) => ipcRenderer.invoke("open-file", payload),
  fetchSRTMTile: (z, x, y) => ipcRenderer.invoke("fetch-srtm-tile", { z, x, y }),
  fetchWebLayerUrl: (url) => ipcRenderer.invoke("fetch-web-layer", { url }),
  dbTest: (config) => ipcRenderer.invoke("db-test", config),
  dbQuery: (config, sql) => ipcRenderer.invoke("db-query", { config, sql }),
  dbListTables: (config) => ipcRenderer.invoke("db-list-tables", config),
  dbConnect: (config) => ipcRenderer.invoke("db-connect", config),
  dbDisconnect: (id) => ipcRenderer.invoke("db-disconnect", { id }),
  dbLiveList: () => ipcRenderer.invoke("db-live-list"),
  dbLiveQuery: (id, sql) => ipcRenderer.invoke("db-live-query", { id, sql }),
  dbLiveListTables: (id) => ipcRenderer.invoke("db-live-list-tables", { id }),
  fsListDir: (dirPath) => ipcRenderer.invoke("fs-list-dir", { dirPath }),
  fsListDrives: () => ipcRenderer.invoke("fs-list-drives"),
  fsReadFile: (filePath) => ipcRenderer.invoke("fs-read-file", { filePath }),
  autosaveWrite: (payload) => ipcRenderer.invoke("autosave-write", payload),
  autosaveRead: () => ipcRenderer.invoke("autosave-read"),
  autosaveClear: () => ipcRenderer.invoke("autosave-clear"),
  onSectionData: (cb) => { const h = (_e, d) => cb(d); ipcRenderer.on("section-data", h); return () => ipcRenderer.removeListener("section-data", h); },
  onMenu: (cb) => { const h = (_e, action) => cb(action); ipcRenderer.on("menu", h); return () => ipcRenderer.removeListener("menu", h); },
});
