// TASKS.csv #445 step 4 — memoised lucide icons. Measured (Vite dev, Harry loaded, 3D View visible): of ~11 ms of
// component time per ViewerModule re-render, ~6 ms was lucide icons — each is a forwardRef component and re-rendered
// on every store edit or toggle although its props (size, colour, style) hadn't changed. These are the same icons,
// memo-wrapped: an icon re-renders only when a prop changes. `style` is compared by its values (an inline
// style={{...}} is a new object each render but usually the same values), which is exactly what it draws.
// Same export names as lucide-react, so a file switches by changing only its import source.
import { memo } from "react";
import * as L from "lucide-react";

const sameStyle = (a, b) => {
  if (a === b) return true;
  if (!a || !b) return false;
  const ka = Object.keys(a), kb = Object.keys(b);
  return ka.length === kb.length && ka.every((k) => a[k] === b[k]);
};
const sameProps = (p, q) => {
  const kp = Object.keys(p), kq = Object.keys(q);
  return kp.length === kq.length && kp.every((k) => (k === "style" ? sameStyle(p.style, q.style) : p[k] === q[k]));
};
export const memoIcon = (Icon) => memo(Icon, sameProps);

export const Activity = memoIcon(L.Activity);
export const AlertTriangle = memoIcon(L.AlertTriangle);
export const AlignCenter = memoIcon(L.AlignCenter);
export const AlignLeft = memoIcon(L.AlignLeft);
export const AlignRight = memoIcon(L.AlignRight);
export const ArrowDownToLine = memoIcon(L.ArrowDownToLine);
export const ArrowRight = memoIcon(L.ArrowRight);
export const ArrowUpRight = memoIcon(L.ArrowUpRight);
export const Award = memoIcon(L.Award);
export const BarChart3 = memoIcon(L.BarChart3);
export const Beaker = memoIcon(L.Beaker);
export const Bold = memoIcon(L.Bold);
export const Bookmark = memoIcon(L.Bookmark);
export const BookmarkPlus = memoIcon(L.BookmarkPlus);
export const Box = memoIcon(L.Box);
export const Calculator = memoIcon(L.Calculator);
export const Camera = memoIcon(L.Camera);
export const Check = memoIcon(L.Check);
export const CheckCircle2 = memoIcon(L.CheckCircle2);
export const CheckSquare = memoIcon(L.CheckSquare);
export const ChevronDown = memoIcon(L.ChevronDown);
export const ChevronRight = memoIcon(L.ChevronRight);
export const ChevronUp = memoIcon(L.ChevronUp);
export const Circle = memoIcon(L.Circle);
export const Compass = memoIcon(L.Compass);
export const Cpu = memoIcon(L.Cpu);
export const Crosshair = memoIcon(L.Crosshair);
export const Database = memoIcon(L.Database);
export const Download = memoIcon(L.Download);
export const Droplets = memoIcon(L.Droplets);
export const Eye = memoIcon(L.Eye);
export const EyeOff = memoIcon(L.EyeOff);
export const File = memoIcon(L.File);
export const FileBarChart2 = memoIcon(L.FileBarChart2);
export const FileDown = memoIcon(L.FileDown);
export const FilePlus2 = memoIcon(L.FilePlus2);
export const FileSpreadsheet = memoIcon(L.FileSpreadsheet);
export const FileText = memoIcon(L.FileText);
export const Flag = memoIcon(L.Flag);
export const FlaskConical = memoIcon(L.FlaskConical);
export const Folder = memoIcon(L.Folder);
export const FolderOpen = memoIcon(L.FolderOpen);
export const Gauge = memoIcon(L.Gauge);
export const Gem = memoIcon(L.Gem);
export const GitCompare = memoIcon(L.GitCompare);
export const GitCompareArrows = memoIcon(L.GitCompareArrows);
export const GitFork = memoIcon(L.GitFork);
export const Globe = memoIcon(L.Globe);
export const Globe2 = memoIcon(L.Globe2);
export const Grid3x3 = memoIcon(L.Grid3x3);
export const Group = memoIcon(L.Group);
export const Hand = memoIcon(L.Hand);
export const HardDrive = memoIcon(L.HardDrive);
export const Image = memoIcon(L.Image);
export const Info = memoIcon(L.Info);
export const Italic = memoIcon(L.Italic);
export const Keyboard = memoIcon(L.Keyboard);
export const Layers = memoIcon(L.Layers);
export const Layers3 = memoIcon(L.Layers3);
export const Layout = memoIcon(L.Layout);
export const LayoutGrid = memoIcon(L.LayoutGrid);
export const LayoutTemplate = memoIcon(L.LayoutTemplate);
export const ListFilter = memoIcon(L.ListFilter);
export const Loader2 = memoIcon(L.Loader2);
export const LogIn = memoIcon(L.LogIn);
export const Magnet = memoIcon(L.Magnet);
export const Map = memoIcon(L.Map);
export const MapPin = memoIcon(L.MapPin);
export const MapPinned = memoIcon(L.MapPinned);
export const Maximize2 = memoIcon(L.Maximize2);
export const MessageSquare = memoIcon(L.MessageSquare);
export const Milestone = memoIcon(L.Milestone);
export const Minus = memoIcon(L.Minus);
export const MonitorPlay = memoIcon(L.MonitorPlay);
export const Mountain = memoIcon(L.Mountain);
export const Move = memoIcon(L.Move);
export const Package = memoIcon(L.Package);
export const PackageOpen = memoIcon(L.PackageOpen);
export const Palette = memoIcon(L.Palette);
export const Pencil = memoIcon(L.Pencil);
export const Play = memoIcon(L.Play);
export const Plus = memoIcon(L.Plus);
export const Radar = memoIcon(L.Radar);
export const Radio = memoIcon(L.Radio);
export const Redo2 = memoIcon(L.Redo2);
export const RefreshCw = memoIcon(L.RefreshCw);
export const RotateCcw = memoIcon(L.RotateCcw);
export const Rows3 = memoIcon(L.Rows3);
export const Ruler = memoIcon(L.Ruler);
export const Satellite = memoIcon(L.Satellite);
export const Save = memoIcon(L.Save);
export const Scale = memoIcon(L.Scale);
export const ScatterChart = memoIcon(L.ScatterChart);
export const Scissors = memoIcon(L.Scissors);
export const Settings = memoIcon(L.Settings);
export const Settings2 = memoIcon(L.Settings2);
export const Shapes = memoIcon(L.Shapes);
export const Sheet = memoIcon(L.Sheet);
export const ShieldAlert = memoIcon(L.ShieldAlert);
export const ShieldCheck = memoIcon(L.ShieldCheck);
export const Sigma = memoIcon(L.Sigma);
export const SlidersHorizontal = memoIcon(L.SlidersHorizontal);
export const Spline = memoIcon(L.Spline);
export const Square = memoIcon(L.Square);
export const SquareSplitVertical = memoIcon(L.SquareSplitVertical);
export const Star = memoIcon(L.Star);
export const Target = memoIcon(L.Target);
export const TerminalSquare = memoIcon(L.TerminalSquare);
export const Trash2 = memoIcon(L.Trash2);
export const Triangle = memoIcon(L.Triangle);
export const Type = memoIcon(L.Type);
export const Undo2 = memoIcon(L.Undo2);
export const Unplug = memoIcon(L.Unplug);
export const Upload = memoIcon(L.Upload);
export const Waves = memoIcon(L.Waves);
export const Waypoints = memoIcon(L.Waypoints);
export const X = memoIcon(L.X);
export const Zap = memoIcon(L.Zap);
